#!/bin/bash
read -p "User: " -e user

if [ "$os_name" == "Ubuntu" ]
then
         killall -9 -u $user > /dev/null 2>&1
         userdel -f -r $user > /dev/null 2>&1
elif [ "$os_name" == "Debian" ]
then
        deluser=$(ps aux | grep "${user} \[priv\]" | sort -k 72 | awk '{print $2}')
        kill "${deluser}"
        killall -u $user > /dev/null 2>&1
        userdel -f -r $user > /dev/null 2>&1
elif [ "$os_name" == "CentOS" ]
then
        pkill -u $user > /dev/null 2>&1
        userdel $user > /dev/null 2>&1
fi

###################################
TOKEN=$(cat /etc/lukman/bot_token)
CHAT_ID="-1001826411896"
domain=$(cat /etc/xray/domain)

MESSAGE="<pre>┌───────────────────────────┐
         SSH INFORMATION
└───────────────────────────┘
┌───────────────────────────┐
  Domain   : \$domain
  Username : \$user
  Status   : Deleted account
└───────────────────────────┘</pre>"

MESSAGE=$(echo "$MESSAGE" | sed "s/\$domain/$domain/g" | sed "s/\$user/$user/g")
curl -s -X POST "https://api.telegram.org/bot$TOKEN/sendMessage" -d "chat_id=$CHAT_ID" -d "parse_mode=HTML" -d "text=$MESSAGE" > /dev/null
###################################
