#!/bin/bash
red='\e[1;31m'
green='\e[0;32m'
NC='\e[0m'

IP=$(cat /root/ip);
domain=$(cat /etc/xray/domain)

read -p "Username : " Login
read -p "Password : " Pass

useradd -s /bin/false -M $Login
exp="$(chage -l $Login | grep "Account expires" | awk -F": " '{print $2}')"
echo -e "$Pass\n$Pass\n"|passwd $Login &> /dev/null
echo -e ""
echo -e "Thank You For Using Our Services"
echo -e "SSH Account Info"
echo -e "Username         : $Login "
echo -e "Password         : $Pass"
echo -e "==============================="
echo -e "Domain           : $domain"
echo -e "Host             : $domain"
echo -e "OpenSSH          : "
echo -e "Dropbear         : 109, 143, 443"
echo -e "SSL/TLS          : 443"
echo -e "Port Squid       : "
echo -e "Websocket HTTP   : 80"
echo -e "Websocket HTTPS  : 443"
echo -e "badvpn           : 7100-7300"
echo -e "==============================="
echo -e "PAYLOAD"                                                          
echo -e "GET wss://${domain}/ HTTP/1.1[crlf]Host: [proxy][crlf]Upgrade: websocket[crlf][crlf]"
echo -e "==============================="
echo -e "SETTING PROXY HOST"
echo -e "bug.com:443"
echo -e "==============================="
echo -e "SETING HOST SSH"               
echo -e "$domain:443@$Login:$Pass"
echo -e "==============================="

###################################
TOKEN=$(cat /etc/lukman/bot_token)
CHAT_ID="-1001826411896"

input_file="/etc/xray/domain"
output=""
while IFS= read -r line; do
    sanitized=$(echo "$line" | awk -F'.' '{print toupper(substr($1,1,1)) tolower(substr($1,2))}')
    output="$output $sanitized"
done < "$input_file"
output_upper=$(echo "$output" | tr '[:lower:]' '[:upper:]')
lastdomain="$output_upper"

MESSAGE="<pre>┌─────────────────────────┐
       SSH INFORMATION
└─────────────────────────┘
┌─────────────────────────┐
  ISP      :\$lastdomain
  Username : \$Login
  Status   : Created account
└─────────────────────────┘</pre>"

MESSAGE=$(echo "$MESSAGE" | sed "s/\$lastdomain/$lastdomain/g" | sed "s/\$Login/$Login/g")
curl -s -X POST "https://api.telegram.org/bot$TOKEN/sendMessage" -d "chat_id=$CHAT_ID" -d "parse_mode=HTML" -d "text=$MESSAGE" > /dev/null
###################################
