#!/bin/bash
red='\e[1;31m'
green='\e[0;32m'
NC='\e[0m'

IP=$(cat /etc/lukman/ip);
domain=$(cat /etc/lukman/domain)

read -p "Username : " Login
read -p "Password : " Pass

#useradd -s /bin/false -M $Login
#exp="$(chage -l $Login | grep "Account expires" | awk -F": " '{print $2}')"
#echo -e "$Pass\n$Pass\n"|passwd $Login &> /dev/null

noobzvpns --add-user $Login $Pass

###################################
TOKEN=$(cat /etc/lukman/bot_token)
CHAT_ID="-1001826411896"

input_file="/etc/lukman/domain"
output=""
while IFS= read -r line; do
    sanitized=$(echo "$line" | awk -F'.' '{print toupper(substr($1,1,1)) tolower(substr($1,2))}')
    output="$output $sanitized"
done < "$input_file"
output_upper=$(echo "$output" | tr '[:lower:]' '[:upper:]')
lastdomain="$output_upper"

MESSAGE="<pre>┌─────────────────────────┐
     • NOOBZ INFORMATION •
└─────────────────────────┘
┌─────────────────────────┐
  ISP      :\$lastdomain
  Username : \$Login
  Status   : Created 🟢
└─────────────────────────┘</pre>"

MESSAGE=$(echo "$MESSAGE" | sed "s/\$lastdomain/$lastdomain/g" | sed "s/\$Login/$Login/g")
curl -s -X POST "https://api.telegram.org/bot$TOKEN/sendMessage" -d "chat_id=$CHAT_ID" -d "parse_mode=HTML" -d "text=$MESSAGE" > /dev/null
###################################

clear
echo -e "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" | tee -a /etc/log-create-user.log
echo -e "         Noobzvpn Account Account      " | tee -a /etc/log-create-user.log
echo -e "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" | tee -a /etc/log-create-user.log
echo -e "Username       : $Login "
echo -e "Password       : $Pass"
echo -e "Remarks : $Login" | tee -a /etc/log-create-user.log
echo -e "Domain : $domain" | tee -a /etc/log-create-user.log
echo -e "==============================="
