#!/bin/bash
read -p "User: " -e user

noobzvpns --remove-user $user

###################################
TOKEN=$(cat /etc/lukman/bot_token)
CHAT_ID="-1001826411896"

input_file="/etc/lukman/domain"
output=""
while IFS= read -r line; do
    sanitized=$(echo "$line" | awk -F'.' '{print toupper(substr($1,1,1)) tolower(substr($1,2))}')
    output="$output $sanitized"
done < "$input_file"
output_upper=$(echo "$output" | tr '[:lower:]' '[:upper:]')
lastdomain="$output_upper"

MESSAGE="<pre>┌─────────────────────────┐
     • NOOBZ INFORMATION •
└─────────────────────────┘
┌─────────────────────────┐
  ISP      :\$lastdomain
  Username : \$user
  Status   : Deleted 🔴
└─────────────────────────┘</pre>"

MESSAGE=$(echo "$MESSAGE" | sed "s/\$lastdomain/$lastdomain/g" | sed "s/\$user/$user/g")
curl -s -X POST "https://api.telegram.org/bot$TOKEN/sendMessage" -d "chat_id=$CHAT_ID" -d "parse_mode=HTML" -d "text=$MESSAGE" > /dev/null
###################################
